name: fancy_on_boarding
description: A Flutter package for a quick, handy and beautiful OnBoarding screen library.
version: 1.1.0
author: Sahil Kumar <xdsahil@gmail.com>
homepage: https://github.com/xsahil03x/fancy_on_boarding

dependencies:
  flutter_svg: ^0.10.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

flutter:
